Repository codeit-globalnomad/globalnomad, pull requests merged in 2025-03, with the labels that each got.

#18 [#14] feat/공통컴포넌트 헤더
  src/app/globals.css
  src/assets/icons/bell-hover.svg
  src/assets/icons/bell.svg
  src/components/Header.tsx
  src/stories/Header.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#20 [#13] feat/공통API 내체험
  src/app/api/[...endpoint]/route.ts
  src/lib/apis/myActivities.ts
  src/lib/hooks/useMyActivities.ts
  src/lib/types/myActivities.ts
Labels: Priority : High 🔴, Type : Feature ✨

#23 [#22] feat/공통컴포넌트 푸터
  src/components/Footer.tsx
  src/stories/Footer.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#26 [#16] feat/공통API 체험
  src/lib/apis/activities.ts
  src/lib/hooks/useActivities.ts
  src/lib/types/activities.ts
Labels: Priority : High 🔴, Type : Feature ✨

#29 [#27] feat/공통API 로그인, 토큰재발급
  src/lib/apis/auth.ts
  src/lib/hooks/useAuth.ts
  src/lib/types/auth.ts
Labels: Priority : High 🔴, Type : Feature ✨

#30 [#21] feat/공통API 내예약
  src/lib/apis/myReservation.ts
  src/lib/hooks/useMyReservation.ts
  src/lib/types/myReservation.ts
Labels: Priority : High 🔴, Type : Feature ✨

#25 [#15] feat/공통API 회원가입 내정보
  src/lib/apis/users.ts
  src/lib/hooks/useUsers.ts
  src/lib/types/users.ts
Labels: Priority : High 🔴, Type : Feature ✨

#31 [#17] feat/공통API 내 알림 작업
  src/lib/apis/myNotifications.ts
  src/lib/hooks/useMyNotification.ts
  src/lib/types/myNotification.ts
Labels: Priority : High 🔴, Type : Feature ✨

#34 [#28] feat/간편로그인 API 추상화
  src/lib/apis/oauth.ts
  src/lib/hooks/useOauth.ts
  src/lib/types/oauth.ts
Labels: Priority : High 🔴, Type : Feature ✨

#35 [#32] refactor/공통컴포넌트 버튼
  src/app/(with-nav-footer)/(mypage)/my-page/page.tsx
  src/components/Button.tsx
  src/components/Buttons.tsx
  src/stories/Button.stories.tsx
  src/stories/Buttons.stories.tsx
  src/stories/Modal.stories.tsx
Labels: Priority : Low 🟢, Type : Refactor ♻️

#45 [#44] feat/회원가입페이지 UI 구현
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/oauth/signup/[...provider]/route.tsx
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/app/(auth)/signup/_components/SocialButtons.tsx
  src/app/(with-nav-footer)/(mypage)/my-page/page.tsx
  src/lib/network/extractProviderAndCode.ts
  src/lib/types/users.ts
  src/middleware.ts
  src/stories/Modal.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#42 [#37] refactor/공통API 일관성 개선
  src/lib/apis/activities.ts
  src/lib/apis/myActivities.ts
  src/lib/apis/myNotifications.ts
  src/lib/apis/myReservation.ts
  src/lib/apis/oauth.ts
  src/lib/apis/users.ts
  src/lib/hooks/useActivities.ts
  src/lib/hooks/useAuth.ts
  src/lib/hooks/useMyActivities.ts
  src/lib/hooks/useMyNotification.ts
  src/lib/hooks/useMyReservation.ts
  src/lib/hooks/useOauth.ts
  src/lib/hooks/useUsers.ts
  src/lib/types/activities.ts
  src/lib/types/auth.ts
  src/lib/types/myActivities.ts
  src/lib/types/myNotification.ts
  src/lib/types/myReservation.ts
  src/lib/types/oauth.ts
  src/lib/types/users.ts
Labels: Priority : High 🔴, Type : Refactor ♻️

#48 [#46] feat/공통컴포넌트 인풋
  src/components/Input.tsx
  src/stories/Input.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#49 [#33} feat/공통컴포넌트 페이지네이션
  src/assets/icons/pagination-right-arrow.svg
  src/components/Pagination.tsx
  src/stories/Pagination.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#50 [#36] feat/공통컴포넌트 드롭다운
  src/assets/icons/arrow-filter-dropdown.svg
  src/assets/icons/kebab.svg
  src/components/Dropdown.tsx
  src/components/FilterDropdown.tsx
  src/stories/Dropdown.stories.tsx
  src/stories/FilterDropdown.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#54 [#52] feat/체험목록페이지 서치바
  src/app/(with-nav-footer)/activities/_components/SearchBar.tsx
  src/app/(with-nav-footer)/activities/page.tsx
  src/components/Footer.tsx
  src/components/Input.tsx
  src/stories/Input.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#56 [#53] feat/예약현황페이지 달력UI
  package-lock.json
  package.json
  src/app/(with-nav-footer)/(mypage)/my-reservations/_compontents/MyCalendar.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_compontents/myCalendar.css
  src/assets/icons/calendar-next.svg
  src/assets/icons/calendar-prev.svg
  src/stories/MyReservationCalendar.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#59 [#55] feat/체험목록페이지 인기 체험
  package-lock.json
  package.json
  src/app/(with-nav-footer)/activities/_components/BestActivities.tsx
  src/app/(with-nav-footer)/activities/_components/BestActivityItem.tsx
  src/app/(with-nav-footer)/activities/page.tsx
  src/assets/icons/left-arrow.svg
  src/assets/icons/right-arrow.svg
  src/lib/utils/useMediaQuery.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#62 [#51] feat/공통컴포넌트 사이드네비게이션메뉴
  src/components/ProfileImage.tsx
  src/components/SideNavMenu.tsx
  src/stories/SideNavMenu.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#67 [#47] feat/체험상세페이지 구조화
  package-lock.json
  src/app/(with-nav-footer)/activities/[id]/.gitkeep
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityBanner.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityDescription.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityDescriptionSection.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityGallery.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityHeader.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityLocation.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityLocationSection.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/DesktopReservation.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/MobileReservation.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/TabletReservation.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/index.ts
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReviews.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReviewsSection.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityTab.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/LoadingSpinner.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ScrollToTopButton.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/index.tsx
  src/app/(with-nav-footer)/activities/[id]/_compontents/.gitkeep
  src/app/(with-nav-footer)/activities/[id]/page.tsx
  src/assets/icons/marker.svg
  src/assets/icons/top-arrow.svg
  src/components/Footer.tsx
  src/lib/utils/useIntersectionObserver.ts
Labels: Priority : Normal 🔵, Type : Feature ✨

#69 [#64] Feat/마이페이지 레이아웃
  src/app/(with-nav-footer)/(mypage)/layout.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/page.tsx
  src/components/SideNavMenu.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#70 [#58] feat/로그인 페이지
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/oauth/status/route.ts
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/app/(auth)/signup/_components/SocialButtons.tsx
  src/app/(with-nav-footer)/layout.tsx
  src/components/FloatingLabelInput.tsx
  src/components/Header.tsx
  src/components/Input.tsx
  src/lib/apis/auth.ts
  src/lib/hooks/useUsers.ts
  src/lib/network/axiosClientHelper.ts
  src/lib/network/axiosServerHelper.ts
  src/lib/types/auth.ts
  src/lib/types/users.ts
  src/middleware.ts
Labels: Priority : Normal 🔵, Type : Feature ✨

#73 [#68] feat/체험상세페이지 상단헤더
  package-lock.json
  package.json
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityHeader.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/FacebookShare.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/KakaoShare.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/index.tsx
  src/app/(with-nav-footer)/activities/[id]/page.tsx
  src/app/layout.tsx
  src/assets/icons/share-facebook.svg
  src/assets/icons/share-kakao.svg
  src/assets/icons/share-url.svg
  src/assets/icons/share-x.svg
  src/assets/icons/share.svg
  src/components/Header.tsx
  src/components/LoadingSpinner.tsx
  src/components/Modal.tsx
  src/global.d.ts
  src/stories/Modal.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#76 [#66] feat/체험목록페이지 모든 체험
  src/app/(with-nav-footer)/activities/_components/AllActivities.tsx
  src/app/(with-nav-footer)/activities/_components/AllActivityItem.tsx
  src/app/(with-nav-footer)/activities/_components/BestActivities.tsx
  src/app/(with-nav-footer)/activities/_components/Category.tsx
  src/app/(with-nav-footer)/activities/page.tsx
  src/assets/icons/category-arrow-left.svg
  src/components/FilterDropdown.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#75 [#71] feat/예약내역페이지 예약 카드
  src/app/(with-nav-footer)/(mypage)/my-reservations/_compontents/MyReservationCard.tsx
  src/components/SideNavMenu.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#80 [#74] feat/체험상세페이지 이미지갤러리
  package-lock.json
  package.json
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityBanner.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityGallery.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/index.tsx
  src/assets/icons/left-arrow-white.svg
  src/assets/icons/pause.svg
  src/assets/icons/play.svg
Labels: Priority : Normal 🔵, Type : Feature ✨

#79 [#57] feat/예약현황페이지 체험필터
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/_compontents/MyActivityFilter.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/MyReservation.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/MyCalendar.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/myCalendar.css
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/page.tsx
  src/components/FilterDropdown.tsx
  src/components/SideNavMenu.tsx
  src/stories/MyReservationCalendar.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#82 [#72] feat/내정보페이지
  src/app/(with-nav-footer)/(mypage)/layout.tsx
  src/app/(with-nav-footer)/(mypage)/my-page/_components/MyPageForm.tsx
  src/app/(with-nav-footer)/(mypage)/my-page/_compontents/.gitkeep
  src/app/(with-nav-footer)/(mypage)/my-page/page.tsx
  src/app/api/[...endpoint]/route.ts
  src/components/ProfileImage.tsx
  src/components/SideNavMenu.tsx
  src/lib/apis/users.ts
  src/lib/contexts/ProfileImageContext.tsx
  src/lib/hooks/useUsers.ts
  src/lib/network/axiosServerHelper.ts
  src/lib/types/auth.ts
  src/lib/types/users.ts
  src/stories/Input.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#85 [#81] feat/체험상세페이지 설명지도
  package-lock.json
  package.json
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityDescription.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityDescriptionSection.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityGallery.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityLocation.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityLocationSection.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/index.tsx
  src/global.d.ts
Labels: Priority : Normal 🔵, Type : Feature ✨

#88 [#77] feat/예약내역페이지 취소/후기모달
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/.gitkeep
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/CancelReservationModal.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/MyCalendar.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/MyReservationCard.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/WriteReviewModal.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/myCalendar.css
  src/app/(with-nav-footer)/(mypage)/my-reservations/_compontents/MyReservationCard.tsx
  src/assets/icons/check-circle-filled.svg
  src/components/Modal.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#86 [#84] fix/내브바 로딩 작업 및 드롭다운 작업
  src/app/(auth)/oauth/status/route.ts
  src/app/api/[...endpoint]/route.ts
  src/components/Header.tsx
  src/components/ProfileImage.tsx
  src/components/auth/LoadingSkeleton.tsx
  src/components/auth/LoggedInHeader.tsx
  src/components/auth/LoggedOutHeader.tsx
  src/components/auth/logoutAction.ts
  src/lib/network/axiosServerHelper.ts
Labels: Priority : Low 🟢, Type : Enhancement 🚀

#89 [#78] feat/체험목록페이지 검색 기능
  src/app/(with-nav-footer)/activities/_components/ActivityList.tsx
  src/app/(with-nav-footer)/activities/_components/AllActivities.tsx
  src/app/(with-nav-footer)/activities/_components/BestActivities.tsx
  src/app/(with-nav-footer)/activities/_components/Category.tsx
  src/app/(with-nav-footer)/activities/_components/FloatingLabelInput.tsx
  src/app/(with-nav-footer)/activities/_components/SearchBar.tsx
  src/app/(with-nav-footer)/activities/page.tsx
Labels: Priority : High 🔴, Type : Feature ✨

#92 [#91] refactor/로그인관련 모달 토스트 작업
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/app/layout.tsx
  src/components/Modal.tsx
  src/components/auth/LoggedInHeader.tsx
  src/lib/network/axiosServerHelper.ts
Labels: Priority : Low 🟢, Type : Refactor ♻️

#94 [#83] feat/예약현황페이지 예약현황조회
  src/app/(with-nav-footer)/(mypage)/layout.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/MyReservation.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/MyActivitiesReservations.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/MyActivityFilter.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/MyCalendar.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/ReservationCardList.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/ReservationDetails.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/page.tsx
  src/assets/icons/No-data.svg
  src/components/SideNavMenu.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#98 [#90] feat/체험관리페이지 체험카드
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/MyActivities.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/MyActivityCard.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-page/_components/MyPageForm.tsx
  src/components/Header.tsx
  src/components/SideNavMenu.tsx
  src/stories/Header.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#100 [#95] feat/예약내역페이지 페이지 구현
  src/app/(with-nav-footer)/(mypage)/my-reservations/.gitkeep
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/.gitkeep
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/MyCalendar.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/MyReservations.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/myCalendar.css
  src/app/(with-nav-footer)/(mypage)/my-reservations/page.tsx
  src/lib/hooks/useMyReservation.ts
Labels: Priority : Normal 🔵, Type : Feature ✨
