Repository codeit-globalnomad/globalnomad, pull requests merged in 2025-04, with the labels that each got.

#106 [#102] refactor/체험목록페이지 배너 슬라이드
  src/app/(with-nav-footer)/activities/_components/Banner.tsx
  src/app/(with-nav-footer)/activities/_components/BannerSkeleton.tsx
Labels: Priority : Normal 🔵, Type : Refactor ♻️

#109 [#107] feat/랜딩페이지
  package-lock.json
  package.json
  src/app/(with-nav-footer)/(landing)/_components/MainBanner.tsx
  src/app/(with-nav-footer)/(landing)/_components/MainSection.tsx
  src/app/(with-nav-footer)/(landing)/_compontents/.gitkeep
  src/app/(with-nav-footer)/(landing)/page.tsx
  src/app/globals.css
  src/assets/images/banner.jpg
  src/assets/images/gradients.png
  src/assets/images/section1-lg.jpg
  src/assets/images/section1-md.jpg
  src/assets/images/section2-lg.jpg
  src/assets/images/section2-md.jpg
  src/assets/images/section3-lg.jpg
  src/assets/images/section3-md.jpg
  src/assets/logo/logo-lg.svg
  src/assets/logo/logo-md-white.svg
  src/assets/logo/logo-xl-white.svg
Labels: Priority : Normal 🔵, Type : Feature ✨

#114 [#111] feat/공통컴포넌트 404, 에러 처리
  src/app/(with-nav-footer)/activities/_components/ActivityList.tsx
  src/app/(with-nav-footer)/activities/_components/Banner.tsx
  src/app/not-found.tsx
  src/components/RetryError.tsx
Labels: Priority : Low 🟢, Type : Feature ✨

#110 [#99] feat/내체험관리페이지 체험등록
  package-lock.json
  package.json
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/ActivityForm.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/AddressFind.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/DatepickerStyles.ts
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/ImageUploader.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/SchduleList.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/_components/AddActivities.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/_components/AddressFind.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/_components/DatepickerStyles.ts
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/_components/ImageUploader.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/_components/SchduleList.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/page.tsx
  src/components/FilterDropdown.tsx
  src/components/auth/logoutAction.ts
  src/lib/hooks/useMyActivities.ts
  src/lib/types/activities.ts
  src/stories/Dropdown.stories.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#121 [#115] refactor/체험목록페이지
  src/app/(with-nav-footer)/activities/_components/ActivityList.tsx
  src/app/(with-nav-footer)/activities/_components/AllActivities.tsx
  src/app/(with-nav-footer)/activities/_components/AllActivityItem.tsx
  src/app/(with-nav-footer)/activities/_components/Banner.tsx
  src/app/(with-nav-footer)/activities/_components/BestActivities.tsx
  src/app/(with-nav-footer)/activities/_components/BestActivitiesBanner.tsx
  src/app/(with-nav-footer)/activities/_components/BestActivitiesBannerSkeleton.tsx
  src/app/(with-nav-footer)/activities/_components/BestActivityItem.tsx
  src/app/(with-nav-footer)/activities/_components/Category.tsx
  src/app/(with-nav-footer)/activities/_components/FloatingLabelInput.tsx
  src/app/(with-nav-footer)/activities/_components/SearchBar.tsx
  src/app/(with-nav-footer)/activities/page.tsx
  src/app/layout.tsx
Labels: Priority : Low 🟢, Type : Refactor ♻️

#118 [#108] feat/예약현황페이지 팝업창
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/MyReservation.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/MyActivitiesReservations.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/MyActivityFilter.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/MyCalendar.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/NoReservations.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/ReservationCardList.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/ReservationDetails.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/ReservationStatusTabs.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/ReservationsTimeSelect.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/myCalendar.css
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/reservation-dashboard/page.tsx
  src/components/SideNavMenu.tsx
  src/lib/hooks/useMyActivities.ts
  src/lib/types/myActivities.ts
  src/lib/utils/useVIewPortWidth.ts
Labels: Priority : Normal 🔵, Type : Feature ✨

#123 [#119] feat/공통컴포넌트 Empty
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/CancelReservationModal.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/MyReservationCard.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/MyReservations.tsx
  src/components/Empty.tsx
  src/components/SideNavMenu.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨, Type : Refactor ♻️

#124 [#122] refactor/공통컴포넌트 헤더, 푸터, 프로필 이미지 등 리팩토링
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/app/(auth)/signup/_components/SocialButtons.tsx
  src/app/(with-nav-footer)/activities/_components/ActivityList.tsx
  src/app/(with-nav-footer)/activities/_components/AllActivities.tsx
  src/app/layout.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/LoadingSpinner.tsx
  src/components/Pagination.tsx
  src/components/ProfileImage.tsx
  src/components/auth/HeaderSkeleton.tsx
  src/components/auth/LoadingSkeleton.tsx
  src/components/auth/LoggedInHeader.tsx
  src/components/auth/LoggedOutHeader.tsx
  src/stories/Pagination.stories.tsx
  src/stories/ProfileImage.stories.tsx
Labels: Priority : Low 🟢, Type : Refactor ♻️

#127 [#116] feat/체험관리페이지 체험 수정
  next.config.ts
  package-lock.json
  package.json
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/.gitkeep
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/edit-activities/_components/EditActivities.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/edit-activities/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/.gitkeep
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/ActivityForm.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/AddressFind.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/MyActivityCard.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/SchduleList.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/_components/AddActivities.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/_components/AddressFind.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/_components/DatepickerStyles.ts
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/_components/ImageUploader.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/_components/SchduleList.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-page/_components/MyPageForm.tsx
  src/components/Dropdown.tsx
  src/components/FilterDropdown.tsx
  src/components/auth/LoggedInHeader.tsx
  src/components/auth/logoutAction.ts
  src/lib/apis/myActivities.ts
  src/lib/types/activities.ts
Labels: Priority : Normal 🔵, Type : Feature ✨

#128 [#120] feat/알림
  src/components/auth/LoggedInHeader.tsx
  src/components/auth/NotificationCardList.tsx
  src/components/auth/NotificationDetails.tsx
  src/components/auth/NotificationDropdown.tsx
Labels: Priority : Normal 🔵, Type : Feature ✨

#131 [#125] feat/체험관리페이지 무한스크롤
  src/app/(with-nav-footer)/(mypage)/layout.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/edit-activities/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/ActivityForm.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/AddressFind.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/DeleteActivityModal.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/ImageUploader.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/MyActivities.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/MyActivityCard.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/SchduleList.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-page/_components/MyPageForm.tsx
  src/app/(with-nav-footer)/(mypage)/my-page/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/CancelReservationModal.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/MyReservationCard.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/MyReservations.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/_components/WriteReviewModal.tsx
  src/app/(with-nav-footer)/(mypage)/my-reservations/page.tsx
  src/app/(with-nav-footer)/activities/_components/ActivityList.tsx
  src/app/(with-nav-footer)/mypage-nav/page.tsx
  src/components/FilterDropdown.tsx
  src/components/ProfileImage.tsx
  src/components/SideNavMenu.tsx
  src/lib/hooks/useMyActivities.ts
  src/lib/hooks/useMyReservation.ts
Labels: Priority : High 🔴, Type : Enhancement 🚀, Type : Feature ✨

#133 [Feat/예약내역 리팩토링
  README.md
  src/app/(with-nav-footer)/(mypage)/layout.tsx
  src/components/Pagination.tsx
Labels: Priority : Low 🟢, Type : Refactor ♻️

#136 [#135] refactor/readme 수정
  README.md
Labels: Priority : Low 🟢, Type : Refactor ♻️

#139 [#137] refactor/체험목록페이지 2차 리팩토링
  src/app/(with-nav-footer)/(mypage)/layout.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/edit-activities/_components/EditActivities.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/SchduleList.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/add-activities/_components/AddActivities.tsx
  src/app/(with-nav-footer)/activities/_components/AllActivityItem.tsx
  src/app/(with-nav-footer)/activities/_components/BestActivitiesBanner.tsx
  src/app/(with-nav-footer)/activities/_components/Category.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/components/SideNavMenu.tsx
Labels: Priority : Low 🟢, Type : Enhancement 🚀, Type : Refactor ♻️

#132 [#129] refactor/체험상세페이지 2차 리팩토링
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityBanner.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityDescriptionSection.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityLocationSection.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/ActivityReservationStyles.css
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/AvailableTimeSelector.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/DesktopReservation.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/MobileReservation.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/ReservationCalendar.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/ReservationSubmitButton.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/TabletReservation.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReservation/useReservation.ts
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityReviewsSection.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ActivityTab.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/FacebookShare.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/MoreOptions.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ReviewCard.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/_components/ScrollToTopButton.tsx
  src/app/(with-nav-footer)/activities/[id]/ActivityDetail/index.tsx
  src/app/(with-nav-footer)/activities/[id]/page.tsx
  src/app/layout.tsx
  src/global.d.ts
Labels: Priority : Normal 🔵, Type : Refactor ♻️

#141 [#134] refactor/예약현황페이지 전체
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/MyReservation.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/MyActivitiesReservations.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/MyCalendar.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/ReservationCardList.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/_components/myCalendar.css
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/reservation-dashboard/page.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/reservation-dashboard/page.tsx
  src/lib/hooks/useMyActivities.ts
Labels: Priority : Normal 🔵, Type : Refactor ♻️

#140 [#138] refactor/간편로그인 카카오
  src/app/(auth)/login/_components/LoginForm.tsx
  src/app/(auth)/oauth/signup/[...provider]/route.ts
  src/app/(auth)/signup/_components/ProfileSetupModal.tsx
  src/app/(auth)/signup/_components/SignupForm.tsx
  src/app/(auth)/signup/_components/SocialButtons.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/_compontents/.gitkeep
  src/app/(with-nav-footer)/(mypage)/my-activities/[id]/edit-activities/_components/EditActivities.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/ImageUploader.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/_components/SchduleList.tsx
  src/app/(with-nav-footer)/(mypage)/my-activities/reservation-dashboard/page.tsx
  src/app/api/[...endpoint]/route.ts
  src/app/layout.tsx
  src/components/auth/LoggedInHeader.tsx
  src/components/auth/LoggedOutHeader.tsx
  src/lib/network/axiosServerHelper.ts
  src/lib/network/convertGoogleToken.ts
  src/lib/types/oauth.ts
Labels: Priority : Normal 🔵, Type : Refactor ♻️
